### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by smola** [bigdataref/bigdataref.github.io#10]

**Comment by ajnavarro** [comment]
What version is the best to this type of repos?

**Comment by smola** [comment]
Actually, this is a bit tricky. I would say that all code parts (everything except `icons` and `_data`) should be licensed with the MIT License (one of the most liberal).

README should state that the `icons` folder contains 3rd party images not owned by the bigdataref project and whose copyright is helf by their authors (or something like that).

The tricky part is then the `_data` folder, which is a database of 3rd party info, not our original content/code. One approach is using an [Open Data License](http://opendatacommons.org/licenses/) for that folder, which is designed specifically for databases, or a more general license such as Creative Commons. Honestly, I don't really know the implications of these choices. I'll look into similar projects to see what they're doing.
